import '../models/application.dart';

final List<Application> sampleApplications = [
  Application(
    id: '1',
    companyName: 'Google',
    role: 'SDE Intern',
    source: 'Careers',
    jobLink: 'https://careers.google.com',
    dateApplied: DateTime(2026, 5, 10),
    status: 'Applied',
    notes: 'Referred by friend',
  ),
  Application(
    id: '2',
    companyName: 'Amazon',
    role: 'Backend Intern',
    source: 'LinkedIn',
    jobLink: 'https://amazon.jobs',
    dateApplied: DateTime(2026, 5, 12),
    status: 'OA',
    notes: null,
  ),
  Application(
    id: '3',
    companyName: 'Nokia',
    role: 'Software Intern',
    source: 'Company Site',
    jobLink: 'https://nokia.com/careers',
    dateApplied: DateTime(2026, 5, 15),
    status: 'Interview',
    notes: 'Phone interview scheduled',
  ),
  Application(
    id: '4',
    companyName: 'Microsoft',
    role: 'Full Stack Intern',
    source: 'University Portal',
    jobLink: 'https://careers.microsoft.com',
    dateApplied: DateTime(2026, 5, 8),
    status: 'Selected',
    notes: 'Offer accepted',
  ),
  Application(
    id: '5',
    companyName: 'Apple',
    role: 'iOS Developer Intern',
    source: 'Careers',
    jobLink: 'https://careers.apple.com',
    dateApplied: DateTime(2026, 5, 5),
    status: 'Rejected',
    notes: 'Did not advance to next round',
  ),
  Application(
    id: '6',
    companyName: 'Meta',
    role: 'Backend Engineer Intern',
    source: 'Glassdoor',
    jobLink: 'https://www.metacareers.com',
    dateApplied: DateTime(2026, 6, 1),
    status: 'Applied',
    notes: null,
  ),
];
