spring.application.name=demo

spring.data.mongodb.uri=${MONGODB_URI}
server.port=${PORT:8080}

resume.upload.dir=uploads/resumes

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB