spring.application.name=demo

spring.data.mongodb.uri= mongodb+srv://karthikagrawal05_db_user:iXW9zReOLija9Iuy@job-tracker-cluster.tbh5523.mongodb.net/job_tracker?retryWrites=true&w=majority&appName=job-tracker-cluster
test.message=HELLO_RENDER_DEBUG
server.port=${PORT:8080}

resume.upload.dir=uploads/resumes

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB